name: Mirror to Group Repo

on: [push, delete]

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false


      - name: Push to Group Repository
        env:
          DEST_REPO: "github.com/bebeklab/inspire.git"
          GROUP_TOKEN: ${{ secrets.GROUP_TOKEN }}
        run: |
          git remote add mirror https://${GROUP_TOKEN}@${DEST_REPO}
          git push --mirror mirror
